### ISSUE TITLE
To support /v2.0/lbaas/loadbalancers 

### ISSUE THREAD

**Issue by zoftdev** [kubernetes-sigs/cloud-provider-huaweicloud#101]
Current code connect to classic load balancer with endpoint:
`url := "/v1.0/" + e.elbClient.TenantId + "/elbaas/loadbalancers/" + loadbalancerId`
**What would you like to be added**:
Support share load balancers
` /v2.0/lbaas/loadbalancers `
**Why is this needed**:
 `APIGW.0101 The API does not exist or has not been published in the environment`

**Comment by RainbowMango** [comment]
I guess the shared load balancer is available now.
Please refer to https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/docs/resources/service/annotations.md#specify-load-balancer-class.

**Comment by zoftdev** [comment]
Yes , my fault. Thank you.
