### ISSUE TITLE
CCM not add / remove node pool when scale the workload.

### ISSUE THREAD

**Issue by zoftdev** [kubernetes-sigs/cloud-provider-huaweicloud#104]
**What would you like to be added**:
When workload has been scale up to new node. there are no ensuring event to update backend member in elb.
Same problem when scale down.

**Why is this needed**:
Since design to to send traffic to correct node, ensuring should be fired when workload up/down/scaling

**Comment by RainbowMango** [comment]
That makes sence. Any idea about how to do it?

**Comment by zoftdev** [comment]
May be develop webhook which monitor pod create/terminate and trigger loadbalance ensuring.
