### ISSUE TITLE
Dedicated Load Balancer Support

### ISSUE THREAD

**Issue by rcarre** [kubernetes-sigs/cloud-provider-huaweicloud#112]
> Hi,
> 
> Yes the huaweicloud provider is not supported by RKE but RKE seems to support custom cloud providers.
> 
> They provide [this](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/custom/) example.
> 
> The question is : How can we build and install the huawei cloud provider to be used with RKE ?
> 
> For the configuration, I hope something like openstack cloud provider should work.
> 
> ```
> [Global]
> auth-url = xxxx
> username = xxxx
> password = xxxx
> tenant-id = xxxx
> domain-name = xxxx
> region = xxxx
> 
> [LoadBalancer]
> subnet-id = xxxx
> ```
> 
> Thank you for your help.

Hello @Edge94,
the above configuration looks like Rancher in-tree cloud provider, doesn't it ? What about the alternative to trigger [cloud-provider-huaweicloud](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud) as a Rancher specific external cloud provider instead of [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) which does not support **non-Octavia API compatible** Huawei Cloud Load Balancer. Here is an [example](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/examples/CloudControllerManagerConfigurationExample.json) of such setup.

By the way @RainbowMango, does cloud-provider-huaweicloud plan to support [Dedicated Load Balancers](https://support.huaweicloud.com/intl/en-us/api-elb/CreateLoadBalancer.html) ? Thanks for you support.

_Originally posted by @rcarre in https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/issues/94#issuecomment-1110616257_

**Comment by RainbowMango** [comment]
I'm glad to support the Dedicate Load Balancer, but I'm busy with other stuff, so no plan for it yet :(
