### ISSUE TITLE
Running on version 1.24 huawei-cloud-controller-manager pod is failing with error

### ISSUE THREAD

**Issue by cloudomate** [kubernetes-sigs/cloud-provider-huaweicloud#207]
Hi, 

i am facing issue running this. I have created cloud-config secret as per guide

root@k8s-master-0:~# kubectl get pod -n kube-system | grep huawei-cloud-controller-manager
huawei-cloud-controller-manager-869b854df9-xwm9j   0/1     Error     1 (7s ago)   8s
root@k8s-master-0:~# kubectl logs -n kube-system huawei-cloud-controller-manager-869b854df9-xwm9j
I0313 07:36:57.636259       1 flags.go:64] FLAG: --allocate-node-cidrs="false"
I0313 07:36:57.636301       1 flags.go:64] FLAG: --allow-untagged-cloud="false"
I0313 07:36:57.636304       1 flags.go:64] FLAG: --authentication-kubeconfig=""
I0313 07:36:57.636308       1 flags.go:64] FLAG: --authentication-skip-lookup="false"
I0313 07:36:57.636310       1 flags.go:64] FLAG: --authentication-token-webhook-cache-ttl="10s"
I0313 07:36:57.636313       1 flags.go:64] FLAG: --authentication-tolerate-lookup-failure="false"
I0313 07:36:57.636315       1 flags.go:64] FLAG: --authorization-always-allow-paths="[/healthz,/readyz,/livez]"
I0313 07:36:57.636319       1 flags.go:64] FLAG: --authorization-kubeconfig=""
I0313 07:36:57.636321       1 flags.go:64] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
I0313 07:36:57.636324       1 flags.go:64] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
I0313 07:36:57.636326       1 flags.go:64] FLAG: --bind-address="0.0.0.0"
I0313 07:36:57.636329       1 flags.go:64] FLAG: --cert-dir=""
I0313 07:36:57.636332       1 flags.go:64] FLAG: --cidr-allocator-type="RangeAllocator"
I0313 07:36:57.636334       1 flags.go:64] FLAG: --client-ca-file=""
I0313 07:36:57.636337       1 flags.go:64] FLAG: --cloud-config="/etc/config/cloud-config"
I0313 07:36:57.636339       1 flags.go:64] FLAG: --cloud-provider="huaweicloud"
I0313 07:36:57.636342       1 flags.go:64] FLAG: --cluster-cidr=""
I0313 07:36:57.636344       1 flags.go:64] FLAG: --cluster-name="kubernetes"
I0313 07:36:57.636346       1 flags.go:64] FLAG: --concurrent-service-syncs="1"
I0313 07:36:57.636352       1 flags.go:64] FLAG: --configure-cloud-routes="true"
I0313 07:36:57.636355       1 flags.go:64] FLAG: --contention-profiling="false"
I0313 07:36:57.636357       1 flags.go:64] FLAG: --controller-start-interval="0s"
I0313 07:36:57.636360       1 flags.go:64] FLAG: --controllers="[*]"
I0313 07:36:57.636363       1 flags.go:64] FLAG: --enable-leader-migration="false"
I0313 07:36:57.636366       1 flags.go:64] FLAG: --external-cloud-volume-plugin=""
I0313 07:36:57.636368       1 flags.go:64] FLAG: --feature-gates=""
I0313 07:36:57.636372       1 flags.go:64] FLAG: --help="false"
I0313 07:36:57.636374       1 flags.go:64] FLAG: --http2-max-streams-per-connection="0"
I0313 07:36:57.636377       1 flags.go:64] FLAG: --kube-api-burst="30"
I0313 07:36:57.636379       1 flags.go:64] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0313 07:36:57.636382       1 flags.go:64] FLAG: --kube-api-qps="20"
I0313 07:36:57.636385       1 flags.go:64] FLAG: --kubeconfig=""
I0313 07:36:57.636387       1 flags.go:64] FLAG: --leader-elect="true"
I0313 07:36:57.636390       1 flags.go:64] FLAG: --leader-elect-lease-duration="15s"
I0313 07:36:57.636392       1 flags.go:64] FLAG: --leader-elect-renew-deadline="10s"
I0313 07:36:57.636394       1 flags.go:64] FLAG: --leader-elect-resource-lock="leases"
I0313 07:36:57.636396       1 flags.go:64] FLAG: --leader-elect-resource-name="cloud-controller-manager"
I0313 07:36:57.636399       1 flags.go:64] FLAG: --leader-elect-resource-namespace="kube-system"
I0313 07:36:57.636401       1 flags.go:64] FLAG: --leader-elect-retry-period="2s"
I0313 07:36:57.636404       1 flags.go:64] FLAG: --leader-migration-config=""
I0313 07:36:57.636406       1 flags.go:64] FLAG: --log-flush-frequency="5s"
I0313 07:36:57.636409       1 flags.go:64] FLAG: --master=""
I0313 07:36:57.636412       1 flags.go:64] FLAG: --min-resync-period="12h0m0s"
I0313 07:36:57.636414       1 flags.go:64] FLAG: --node-monitor-period="5s"
I0313 07:36:57.636416       1 flags.go:64] FLAG: --node-status-update-frequency="5m0s"
I0313 07:36:57.636418       1 flags.go:64] FLAG: --node-sync-period="0s"
I0313 07:36:57.636421       1 flags.go:64] FLAG: --permit-address-sharing="false"
I0313 07:36:57.636423       1 flags.go:64] FLAG: --permit-port-sharing="false"
I0313 07:36:57.636425       1 flags.go:64] FLAG: --profiling="true"
I0313 07:36:57.636427       1 flags.go:64] FLAG: --requestheader-allowed-names="[]"
I0313 07:36:57.636429       1 flags.go:64] FLAG: --requestheader-client-ca-file=""
I0313 07:36:57.636432       1 flags.go:64] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I0313 07:36:57.636435       1 flags.go:64] FLAG: --requestheader-group-headers="[x-remote-group]"
I0313 07:36:57.636438       1 flags.go:64] FLAG: --requestheader-username-headers="[x-remote-user]"
I0313 07:36:57.636442       1 flags.go:64] FLAG: --route-reconciliation-period="10s"
I0313 07:36:57.636444       1 flags.go:64] FLAG: --secure-port="10258"
I0313 07:36:57.636447       1 flags.go:64] FLAG: --tls-cert-file=""
I0313 07:36:57.636449       1 flags.go:64] FLAG: --tls-cipher-suites="[]"
I0313 07:36:57.636452       1 flags.go:64] FLAG: --tls-min-version=""
I0313 07:36:57.636454       1 flags.go:64] FLAG: --tls-private-key-file=""
I0313 07:36:57.636456       1 flags.go:64] FLAG: --tls-sni-cert-key="[]"
I0313 07:36:57.636460       1 flags.go:64] FLAG: --use-service-account-credentials="true"
I0313 07:36:57.636462       1 flags.go:64] FLAG: --v="5"
I0313 07:36:57.636465       1 flags.go:64] FLAG: --version="false"
I0313 07:36:57.636477       1 flags.go:64] FLAG: --vmodule=""
I0313 07:36:57.942334       1 serving.go:348] Generated self-signed cert in-memory
W0313 07:36:57.942359       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0313 07:36:58.087733       1 requestheader_controller.go:244] Loaded a new request header values for RequestHeaderAuthRequestController
I0313 07:36:58.088125       1 cloud-controller-manager.go:102] cloudConfig: {"Name":"huaweicloud","CloudConfigFile":"/etc/config/cloud-config"}
F0313 07:36:58.088142       1 plugins.go:154] Couldn't open cloud provider configuration /etc/config/cloud-config: &fs.PathError{Op:"open", Path:"/etc/config/cloud-config", Err:0x2}

If i am right the manifest file has some issues, can you identify and resolve

**Comment by cloudomate** [comment]
thanks i resolved this

**Comment by chengxiangdong** [comment]
I saw your PR(#209 ) and now you are addressing this issue.
