### ISSUE TITLE
typo in loadbalancerconfig.go

### ISSUE THREAD

**Issue by ZoltanPD** [kubernetes-sigs/cloud-provider-huaweicloud#216]
**What happened**:
In the file https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/pkg/config/loadbalancerconfig.go in the LoadELBConfig function you reference an object with wrong name:

	metadataOption := []byte(data["metadataOption"])
	if err := json.Unmarshal(metadataOption, &cfg.MetadataOpts); err != nil {
		klog.Errorf("error parsing metadataOption config: %s", err)
	}

It should be:
	**metadataOptions** := []byte(data["metadataOption"])
	if err := json.Unmarshal(**metadataOptions**, &cfg.MetadataOpts); err != nil {
		klog.Errorf("error parsing metadataOption config: %s", err)
	}

because of this type, doesn't matter what you put as metadataOption it always takes the default values and gives an error that the metadataoption json input has error:

> E0420 07:05:49.335832 1 loadbalancerconfig.go:128] error parsing metadataOption config: unexpected end of JSON input

**What you expected to happen**:
There should be no issue with loading metadata options.

**How to reproduce it (as minimally and precisely as possible)**:
Simply start a controller manager with any value

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.24.2
- Cloud provider or hardware configuration: opentelekomcloud/huaweicloud
- OS (e.g: `cat /etc/os-release`): CentOS 7.9
- Kernel (e.g. `uname -a`): 3.10.0-1160.83.1.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chengxiangdong** [comment]
This seems reasonable to add:

/triage accepted
/priority important-soon
