### ISSUE TITLE
Unable to achieve external ip

### ISSUE THREAD

**Issue by vipcxj** [kubernetes-sigs/cloud-provider-huaweicloud#224]
I have deploied the [cloud-provider-huaweicloud](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud), but there is still no external ip on my nodes. All my nodes have bind eip. The node1 witch running the huawei-cloud-controller-manager is bind two internel ip, one is the local ip, and one is the eip. And there are no eip bind to other nodes, neither internalIp or externalip.

**What you expected to happen**:

I need a way to discovery eip for my nodes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  1.27.4
- Cloud provider or hardware configuration:
  v0.26.3
- OS (e.g: `cat /etc/os-release`):
  Ubuntu 22.04.2 LTS
- Kernel (e.g. `uname -a`):
  Linux node1 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
  calico v3.25.1
- Others:

**Comment by vipcxj** [comment]
```json
{
 "server": {
  "fault": null,
  "id": "XXXX",
  "name": "node4",
  "addresses": {
   "47ed6caf-b823-4ad8-a8eb-7ecdba7d7086": [
    {
     "version": "4",
     "addr": "192.168.0.230",
     "primary": true,
     "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:2e:86:6c",
     "OS-EXT-IPS:type": "fixed",
     "OS-EXT-IPS:port_id": "9cb36757-0583-40f2-bfe3-0174f3bb5d2b"
    },
    {
     "version": "4",
     "addr": "60.204.201.23",
     "primary": true,
     "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:2e:86:6c",
     "OS-EXT-IPS:type": "floating",
     "OS-EXT-IPS:port_id": "9cb36757-0583-40f2-bfe3-0174f3bb5d2b"
    }
   ]
  },
  ...
}
```
根据日志，cloud-provider-manager有调用ecs api的showServer服务，上面是我通过[apiExporter](https://console.huaweicloud.com/apiexplorer/#/openapi/ECS/debug?api=ShowServer)获得的结果，可以看到存在一个floating类型的ip，看cloud-provider-manager的[源码](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/413cb0b0c360786530d6856cbebfd1aebf11195a/pkg/cloudprovider/huaweicloud/wrapper/ecs.go#L135C11-L135C11)，好像floating类型的ip应该是会加入到externalIp中，但实际情况就是没加~ 更奇怪的是node1把这个floating ip给弄成internalip了

**Comment by chengxiangdong** [comment]
Sorry, I didn't quite understand the issue you described.

1. You mentioned that the [source of cloud-provider-manager](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/413cb0b0c360786530d6856cbebfd1aebf11195a/pkg/cloudprovider/huaweicloud/wrapper/ecs.go#L135C11-L135C11), `BuildAddresses` is invoked when obtaining node metadata in the K8s cluster. 
View the infor returned by the API, `name:node4`, the InternalIP and ExternalIP of the node will be returned to the k8s cluster.

2. In the K8s cluster, if you need to provide external services, you can create a `LoadBalancer` service. The service is integrated with ELB through CCM, and ELB forwards external traffic to applications in the k8s cluster, avoiding the need for EIP for each node.

3. I'm not sure what you mean by "I need a way to discovery eip for my nodes" What's the purpose of using EIP for all nodes?

**Comment by vipcxj** [comment]
@chengxiangdong Because I want to deploy a cluster app ([owt-server](https://github.com/open-webrtc-toolkit/owt-server)) which send its node ip or host to the client, then the client will use this ip or host to connect to the cluster directly. I don't know whether it breaks the mechanism of the app if I set all node's ip to a elb ip.

**Comment by chengxiangdong** [comment]
> @chengxiangdong Because I want to deploy a cluster app ([owt-server](https://github.com/open-webrtc-toolkit/owt-server)) which send its node ip or host to the client, then the client will use this ip or host to connect to the cluster directly. I don't know whether it breaks the mechanism of the app if I set all node's ip to a elb ip.

It seems you need to access the "owt-server" application from outside the cluster via the node IP. I'm not certain how you are obtaining the IP of the host where the container is located. However, it's not recommended to access the applications in the cluster through the node IP.

In Kubernetes, a service is a way of exposing a network application running as one or more pods in a cluster. If you need to expose the service to the public network, you can create an loadbalancer serivce and bind EIP through CCM.

For more details about services: https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by vipcxj** [comment]
@chengxiangdong I got a external ip: 192.168.0.247 from the elb. I can't access this ip in the node local. And This is not the eip wihich bind to the elb. What is it?

**Comment by chengxiangdong** [comment]
I will close this question after 30 days of inactivity.

You can reopen this issue with `/reopen`
