### ISSUE TITLE
Add HuaweiCloud to Vendor list at k8s.io

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes-sigs/cloud-provider-huaweicloud#58]
We should add HuaweiCloud to the Vendor list at [Vendor Implementations](https://kubernetes.io/docs/concepts/architecture/cloud-controller/).

cc @kevin-wangzefeng

**Comment by eumel8** [comment]
Interesting! Are there any plans for service extension in compare to OpenStack Cloud Provider?
And which versions of Huawei Cloud are supported?

**Comment by RainbowMango** [comment]
Cloud you please tell me more details about `service extension`?  Then I can confirm. Thanks.

**Comment by eumel8** [comment]
Sure. You started with Loadbalancer (classic and enhanced) which is great. What about Volume Service? Maybe easy to adapt from OpenStack Cinder. 
DNS service would be also interesting (instead in use of external-dns with Designate).

**Comment by RainbowMango** [comment]
@eumel8 Thanks for your information. 
Maybe it's not the right place to track these things, can you raise a new issue for this?

**Comment by eumel8** [comment]
here we are: https://github.com/huawei-cloudnative/cloud-provider-huaweicloud/issues/60
