### ISSUE TITLE
Remove useless method HWSCloud.ScrubDNS()

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes-sigs/cloud-provider-huaweicloud#71]
The method should be deleted.
https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/f9c3d0604192ebf9cc575a3f8762840dc72b6321/pkg/cloudprovider/huaweicloud/huaweicloud.go#L631

**Comment by RainbowMango** [comment]
/cc @Dingshujie

Are you interested in this?

**Comment by Dingshujie** [comment]
> /cc @Dingshujie
> 
> Are you interested in this?

See PR #72
