### ISSUE TITLE
Authentication error when creating service of type LoadBalancer

### ISSUE THREAD

**Issue by irozzo-1A** [kubernetes-sigs/cloud-provider-huaweicloud#76]
HI,

When I create a service of type `LoadBalancer` backed by and ELB using the example manifests and I'm getting the following error:

```
E0701 22:23:20.864914   27379 controller.go:243] error processing service default/classic-service (will retry): failed to ensure load balancer: Failed to GetListenersList : request failed: {"message":"Authorization information is wrong","request_id":"7e70435102c3e74aa64c7110e78aad62"}
```

I don't exclude that it's just a configuration issue, but I double checked it several times and I did not found anything evidently wrong:

```json
{
  "LoadBalancer": {
    "apiserver": "127.0.0.1:8080",
    "secretName": "example.secret",
    "signerType": "ec2",
    "elbAlgorithm": "roundrobin",
    "tenantId": "<MY-PROJECT-ID>",
    "region": "eu-de",
    "vpcId": "<VPC-ID>",
    "subnetId": "<SUBNET-ID>",
    "ecsEndpoint": "https://ecs.eu-de.otc.t-systems.com",
    "elbEndpoint": "https://elb.eu-de.otc.t-systems.com",
    "albEndpoint": "https://elb.eu-de.otc.t-systems.com",
    "vpcEndpoint": "https://vpc.eu-de.otc.t-systems.com",
    "natEndpoint": "https://nat.eu-de.otc.t-systems.com",
    "enterpriseEnable": "false"
  },
  "Auth": {
    "SecretName": "",
    "AccessKey": "<MY-ACCESS_KEY>",
    "SecretKey": "<MY-SECRET-KEY>",
    "IAMEndpoint": "https://iam.eu-de.otc.t-systems.com",
    "DomainID": "<MY-DOMAIN-ID>",
    "ProjectID": "<MY-PROJECT-ID>",
    "Region": "eu-de",
    "Cloud": "otc.t-systems.com"
  }
}
```

And here the secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: example.secret
type: Opaque
data:
  access: <MY-ACCESS-KEY_BASE64>
  secret: <MY-SECRET-KEY_BASE64>
```

I instrumented the code to get some more info and those are request and response:

```
I0702 07:44:40.935961    6830 http.go:129] request sent: GET /v1.0/<MY-PROJECT-ID>/elbaas/listeners HTTP/1.1^M
Host: elb.eu-de.otc.t-systems.com^M
Connection: close^M
Authorization: SDK-HMAC-SHA256 Access=<MY-ACCESS-KEY>, SignedHeaders=x-project-id;x-sdk-date, Signature=<SIGNATURE>^M
X-Project-Id: <MY-PROJECT-ID>^M
X-Sdk-Date: 20200702T074440Z^M
^M

I0702 07:44:40.977038    6830 http.go:155] request received to : HTTP/1.1 401 Unauthorized^M
Connection: close^M
Content-Length: 97^M
Content-Type: application/json^M
Date: Thu, 02 Jul 2020 07:44:40 GMT^M
Server: Web Server^M
^M
{"message":"Authorization information is wrong","request_id":"a37b23c372334707975b54d82df8c3b2"}
```

Note that calls to the server endpoint which rely on the credentials in the `Auth` section, which are the same in the secret, are successful. Any idea?

BTW the [example secret](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/examples/loadbalancers/secret.yaml) seems to be misaligned with [the code](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/0ca8010/pkg/cloudprovider/huaweicloud/huaweicloud.go#L311,L312) which expects `access` and `secret` instead of `access.key` and `secret.key`

**Comment by RainbowMango** [comment]
@Dingshujie Can you help to take a look?

**Comment by RainbowMango** [comment]
> BTW the example secret seems to be misaligned with the code which expects access and secret instead of access.key and secret.key

Wow, yes, the example secret is wrong. The suffix `.key` should be removed.

**Comment by RainbowMango** [comment]
And feel free to send a PR if you want, I mean the example secret thing.

**Comment by irozzo-1A** [comment]
@RainbowMango @Dingshujie I did a small [test](https://github.com/irozzo-1A/huawei-sdk-elb-test/blob/master/main.go) with https://github.com/huaweicloud/golangsdk and I succeeded in listing Listeners and ELBs using same credentials. I noticed some differences on the Authorization header (don't know if this is the root cause of the issue):

Working:
```
Authorization: SDK-HMAC-SHA256 Credential=<MY-ACCESS-KEY>///sdk_request, SignedHeaders=accept;host;user-agent;x-sdk-date, Signature=<SIGNATURE>
```

Not Working:
```
Authorization: SDK-HMAC-SHA256 Access=<MY-ACCESS-KEY>, SignedHeaders=x-project-id;x-sdk-date, Signature=<SIGNATURE>
```

Are both flavours supposed to be supported?

Is there any reason why [golangsdk](https://github.com/huaweicloud/golangsdk) is not used?

Thanks.

**Comment by RainbowMango** [comment]
> Is there any reason why golangsdk is not used?

The only reason is [golangsdk](https://github.com/huaweicloud/golangsdk) not support go module, so I forked one and just enabled Go module, no other code change.

@irozzo-1A 
I'll check if something changed on [golangsdk](https://github.com/huaweicloud/golangsdk) that we need sync accordingly.

I can help to reproduce your issue on my environment and try to dig it out if you'd like to provide a reproducing step.

I'm really sorry for this issue to bother you so long, I'm glad to help.

**Comment by RainbowMango** [comment]
Just found a new [huaweicloud-sdk-go-v3](https://github.com/huaweicloud/huaweicloud-sdk-go-v3) which support Go module. I think we can adapt to the new SDK, but before that, I want to know the root cause post on this issue.

**Comment by irozzo-1A** [comment]
> The only reason is [golangsdk](https://github.com/huaweicloud/golangsdk) not support go module, so I forked one and just enabled Go module, no other code change.

AFAIK this should not be a big problem, especially in this case where the sdk does not have any external dependency. See my example: https://github.com/irozzo-1A/huawei-sdk-elb-test/blob/master/go.mod

> I can help to reproduce your issue on my environment and try to dig it out if you'd like to provide a reproducing step.

1. Create a single node cluster using `local-up-cluster.sh` on a VM running in Huawei cloud. I used Ubuntu 18.06 OS and checked out tag `v1.18.6` on Kubernetes repo (should not be relevant though).

2. Create the following configuration file `provider.conf`

```
{
    "LoadBalancer": {
	"apiserver": "172.17.0.1:8080",
        "secretName": "huawei-ccm-secret",
        "signerType": "ec2",
        "elbAlgorithm": "roundrobin",
        "tenantId": "<MY-TENANT-ID>",
        "region": "eu-de",
        "vpcId": "<MY-VPC-ID>",
        "subnetId": "<MY-SUBNENT-ID>",
        "ecsEndpoint": "https://ecs.eu-de.otc.t-systems.com",
        "elbEndpoint": "https://elb.eu-de.otc.t-systems.com",
        "albEndpoint": "https://elb.eu-de.otc.t-systems.com",
        "vpcEndpoint": "https://vpc.eu-de.otc.t-systems.com",
        "natEndpoint": "https://nat.eu-de.otc.t-systems.com",
        "enterpriseEnable": "false"
    },
    "Auth": {
        "SecretName": "",
        "AccessKey" : "<MY-ACCESS-KEY>",
        "SecretKey" : "<MY-SECRET-KEY>",
        "IAMEndpoint": "https://iam.eu-de.otc.t-systems.com",
	"DomainID": "<DOMAIN-ID>",
        "ProjectID": "<PROJECT-ID>",
        "Region": "eu-de",
        "Cloud": "otc.t-systems.com"
    }
}
```

3. Set the following environment variables:

```
export EXTERNAL_CLOUD_PROVIDER=true
export EXTERNAL_CLOUD_PROVIDER_BINARY=/home/ubuntu/cloud-provider-huaweicloud/huawei-cloud-controller-manager
export CLOUD_PROVIDER="huaweicloud"
export CLOUD_CONFIG=/home/ubuntu/provider.conf

# Why: add elb health check member who must not be 127.0.0.1.
# export HOSTNAME_OVERRIDE="192.168.1.122"

# Why: default --provider-id is hostname for kubelet. We should change it to ecs uuid.
# export KUBELET_PROVIDER_ID="a44af098-7548-4519-8243-a88ba3e5de4f"

# Run conformance testing
export ALLOW_PRIVILEGED=true
export ALLOW_SECURITY_CONTEXT=true
export ENABLE_CRI=false
#export ENABLE_DAEMON=true
export ENABLE_HOSTPATH_PROVISIONER=true
export ENABLE_SINGLE_CA_SIGNER=true
#export HOSTNAME_OVERRIDE=$(ip route get 1.1.1.1 | awk '{print $7}')
export HOSTNAME_OVERRIDE="$(hostname)"
export KUBE_ENABLE_CLUSTER_DASHBOARD=true
export KUBE_ENABLE_CLUSTER_DNS=true
export LOG_LEVEL=10
export KUBELET_HOST="0.0.0.0"
export API_HOST_IP="172.17.0.1"
export API_HOST="172.17.0.1"
```

4. Comment out lines 707-708 in `hack/local-up-cluster.sh` to prevent `KUBELET_PROVIDER_ID` being set:

```
    if [[ "${EXTERNAL_CLOUD_PROVIDER:-}" == "true" ]]; then
       cloud_config_arg=("--cloud-provider=external")
       if [[ "${CLOUD_PROVIDER:-}" == "aws" ]]; then
         cloud_config_arg+=("--provider-id=$(curl http://169.254.169.254/latest/meta-data/instance-id)")
       #else
       #  cloud_config_arg+=("--provider-id=${KUBELET_PROVIDER_ID}")
       fi
    fi
```

5. Run the local cluster:

```
cd kubernetes
hack/install-etcd.sh
export PATH="/home/ubuntu/kubernetes/third_party/etcd:${PATH}"
vim hack/local-up-cluster.sh
```

6. Create the `huawei-ccm-secret`:

```
export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
cluster/kubectl.sh create secret generic huawei-ccm-secret --from-literal="access=<MY-ACCESS-KEY>"  --from-literal="secret=<MY-SECRET-KEY>"
```

7. Create a service of type load balancer

```
cluster/kubectl.sh apply -f ~/cloud-provider-huaweicloud/examples/loadbalancers/service-classic.yaml
```

8. What I expect is that the service gets ready, instead it remains in pending state:

```
cluster/kubectl.sh get svc
NAME              TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
classic-service   LoadBalancer   10.0.0.222   <pending>     80:30260/TCP   18m
kubernetes        ClusterIP      10.0.0.1     <none>        443/TCP        22m
```

And in the logs of cloud-controller-manager I see the following:

```
tail -f /tmp/cloud-controller-manager.log
I0729 22:34:09.103318    2021 controller.go:737] Finished syncing service "default/classic-service" (43.651415ms)
E0729 22:34:09.103350    2021 controller.go:243] error processing service default/classic-service (will retry): failed to ensure load balancer: Failed to GetListenersList : request failed: {"message":"Authorization information is wrong","request_id":"63b0c5b4fccdd642f5b217af39c1cd76"}
, status code: 401
I0729 22:34:09.103617    2021 event.go:281] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"classic-service", UID:"a2bf52ae-d0e4-4558-b8dd-b2d640a23cf4", APIVersion:"v1", ResourceVersion:"435", FieldPath:""}): type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to ensure load balancer: Failed to GetListenersList : request failed: {"message":"Authorization information is wrong","request_id":"63b0c5b4fccdd642f5b217af39c1cd76"}
, status code: 401
```

**Comment by irozzo-1A** [comment]
@RainbowMango note also that I tested with https://github.com/huaweicloud/golangsdk and not https://github.com/huaweicloud/huaweicloud-sdk-go that is the one you forked from, so if we add the one you mentioned I count at least three go SDKs:

- https://github.com/huaweicloud/golangsdk
- https://github.com/huaweicloud/huaweicloud-sdk-go
- https://github.com/huaweicloud/huaweicloud-sdk-go-v3

I used the first because it seems to be the most actively maintained and it's the one used in the terraform [OTC](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/master/go.mod#L12) and [huaweicloud](https://github.com/terraform-providers/terraform-provider-huaweicloud/blob/master/go.mod#L10) providers.

**Comment by Dingshujie** [comment]
> @RainbowMango note also that I tested with https://github.com/huaweicloud/golangsdk and not https://github.com/huaweicloud/huaweicloud-sdk-go that is the one you forked from, so if we add the one you mentioned I count at least three go SDKs:
> 
> * https://github.com/huaweicloud/golangsdk
> * https://github.com/huaweicloud/huaweicloud-sdk-go
> * https://github.com/huaweicloud/huaweicloud-sdk-go-v3
> 
> I used the first because it seems to be the most actively maintained and it's the one used in the terraform [OTC](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/master/go.mod#L12) and [huaweicloud](https://github.com/terraform-providers/terraform-provider-huaweicloud/blob/master/go.mod#L10) providers.
 
Because signature algorithm may different bewteen API Gateway 3 and API Gateway 4.
our repo use newest signature algorithm and test in HuaweiCloud. And OTC may be use old signature algorithm.

**Comment by RainbowMango** [comment]
@irozzo-1A 
This repo now uses a copy of `APIGW-go-sdk-2.0.2` as mentioned by [pkg/apigw/README.md](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/tree/master/pkg/apigw).

**Comment by irozzo-1A** [comment]
@RainbowMango @Dingshujie Thanks for your answers! Would it be an option for you to introduce a fallback mechanism to use the old signature algorithm in case API Gateway 3 is detected (somehow)?

**Comment by RainbowMango** [comment]
> Would it be an option for you to introduce a fallback mechanism to use the old signature algorithm in case API Gateway 3 is detected (somehow)?

I hesitate to support the old signature algorithm, the main reason is  I don't have the necessary environment for testing.

But for your case, maybe you can just add a legacy signature algorithm to `pkg/` and just modify the sign logic in  https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/daa23b8eedfc3723167ef8ae469240aee3da9d88/pkg/cloudprovider/huaweicloud/http.go#L169-L187

**Comment by irozzo-1A** [comment]
@RainbowMango I understand your concern, I think I will fork the project and do as you proposed as a temporary solution until OTC upgrades. Thx for your help!

**Comment by RainbowMango** [comment]
@irozzo-1A Is everything goes alright?

**Comment by irozzo-1A** [comment]
@RainbowMango Thx for asking! I fixed that authentication issue [here](https://github.com/kubermatic-labs/cloud-provider-huaweicloud/pull/1/files) quite easily, but I encountered another issue when trying to create a service of type `LoadBalancer` backed by an ELB.

1. If I understood correctly the ELB has to be created manually after you create the service, do you confirm? https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/pkg/cloudprovider/huaweicloud/elb.go#L300
2. I'm running into this problem:
```
E0806 18:03:13.953961   10474 huaweicloud.go:915] [default/classic-service]Add members of listener(1490147221e442929286cf0ed406c680) error: Failed to AddMembers : request failed: {"error":{"message":"The server and elb is not in the same vpc.","code":"ELB.1001"}}, status code: 400
```
It's weird because the LB and the server seems to be in the same VPC, but I need to double check if I did some mistake in the configuration.

**Comment by irozzo-1A** [comment]
BTW I also tried to apply https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/daa23b8eedfc3723167ef8ae469240aee3da9d88/examples/loadbalancers/service_enhanced_auto.yaml#L1-L20
and it worked fine, apart that I had to remove `"bandwidth_chargemode":"bandwidth"`, because apparently it's unsupported in OTC.

**Comment by RainbowMango** [comment]
> If I understood correctly the ELB has to be created manually after you create the service, do you confirm?

You can create an ELB manually and set the ELB's info to a service's annotations as per [service-anotations](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/docs/resources/service/annotations.md). This is the simplest way I think. 

Here is a [sample service](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/examples/loadbalancers/service_enhanced.yaml).

Just a remember, there are 4 kinds of ELB, the sample above used the `union`, sometimes also called `enhanced`. You need to make sure the ELB service type supported by your environment.

**Comment by RainbowMango** [comment]
> and it worked fine, apart that I had to remove "bandwidth_chargemode":"bandwidth", because apparently it's unsupported in OTC.

Yeah, congrats!  And I can tell that your ELB type is `kubernetes.io/elb.class: union`.

**Comment by RainbowMango** [comment]
> It's weird because the LB and the server seems to be in the same VPC, but I need to double check if I did some mistake in the configuration.

Are you using a classic ELB(not the `kubernetes.io/elb.class: union`)?

**Comment by irozzo-1A** [comment]
> Are you using a classic ELB(not the `kubernetes.io/elb.class: union`)?

Yep, I used this manifest: https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/daa23b8eedfc3723167ef8ae469240aee3da9d88/examples/loadbalancers/service-classic.yaml#L1-L14

**Comment by RainbowMango** [comment]
> E0806 18:03:13.953961   10474 huaweicloud.go:915] [default/classic-service]Add members of listener(1490147221e442929286cf0ed406c680) error: Failed to AddMembers : request failed: {"error":{"message":"The server and elb is not in the same vpc.","code":"ELB.1001"}}, status code: 400

It's pretty weird because the `ELB.1001` error code means a parameter error as per [Error Codes for Classic Load Balancers](https://docs.otc.t-systems.com/api/elb/elb_gc_0001.html).

Any update from you for this issue? And are you sure you need to use both `Classic Load Balancers` and `Enhanced Load Balancers`?

**Comment by RainbowMango** [comment]
Hi @irozzo-1A, any update?

AFAIK, it's recommended to use `Enhanced Load Balancers` instead of the `Classic Load Balancers`.

**Comment by irozzo-1A** [comment]
@RainbowMango sorry for the delay I was in vacation. I'm still having the issue with the `Classic Load Balancer`, I checked again the parameters and I did not find any evident mistake. The server and the ELB are on the same VPC.

I'm not the end user so I cannot say myself if supporting `Classic Load Balancers` is a mandate, what I'm trying to do is to add support for OTC (OpenTelekom Cloud) in Kubermatic (https://github.com/kubermatic/kubermatic/issues/5736), but I think we can consider this as low priority at this stage.

**Comment by RainbowMango** [comment]
> I think we can consider this as low priority at this stage.

Yeah. As far as I know, `Enhanced Load Balancers` fully compatible with `Classic Load Balancers`. And `Classic Load Balancers` is no longer supported in most HUAWEICLOUD regions.

By the way, I have updated the SDK to `huaweicloud-sdk-go-v3` by #84.
