### ISSUE TITLE
I'm having problems trying to deploy huawei-cloud-controller-manager

### ISSUE THREAD

**Issue by czhfe** [kubernetes-sigs/cloud-provider-huaweicloud#78]
I'm having problems trying to deploy huawei-cloud-controller-manager, see The huawei-cloud-controller-manager log has the following message:

W0706 05:18:15.792435       1 throttle.go:265] Throttle config file is not exist.
I0706 05:18:16.091719       1 serving.go:312] Generated self-signed cert in-memory
W0706 05:18:16.838581       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0706 05:18:16.840644       1 controllermanager.go:120] Version: v0.0.0-master+$Format:%h$
I0706 05:18:16.840797       1 config.go:86] Log conf, Auth.IAMEndpoint: iam.cn-south-1.myhuaweicloud.com
I0706 05:18:16.840810       1 config.go:87] Log conf, LoadBalancer.SecretName: cloud-controller-manager-secret
W0706 05:18:16.840933       1 shared_informer.go:386] The specified resyncPeriod 30s is invalid because this shared informer doesn't support resyncing
E0706 05:18:16.841644       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:17.842579       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:18.843384       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:19.844206       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:20.844961       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:21.845657       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:22.846465       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:23.847325       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:24.848067       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0706 05:18:25.848811       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)

**Comment by RainbowMango** [comment]
@Dingshujie Could you please take a look?

**Comment by RainbowMango** [comment]
> E0706 05:18:16.841644 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)

@czhfe It seems like the client can't access kube-apiserver, could you confirm your configuration, especially https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/1ddabdafeb22af74ecb745cf8a733c274364e214/examples/CloudControllerManagerConfigurationExample.json#L3

**Comment by czhfe** [comment]
> > E0706 05:18:16.841644 1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
> 
> @czhfe It seems like the client can't access kube-apiserver, could you confirm your configuration, especially
> 
> https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/1ddabdafeb22af74ecb745cf8a733c274364e214/examples/CloudControllerManagerConfigurationExample.json#L3


Without detailed documentation, I'm guessing the apiserver configuration option is kube-apiserver. I have configured the correct address of the api-server ("apiserver": "127.0.0.1:8080"), and the error I get is the problem I mentioned at the beginning.
