### ISSUE TITLE
Manage security group for LBs

### ISSUE THREAD

**Issue by irozzo-1A** [kubernetes-sigs/cloud-provider-huaweicloud#91]
**What would you like to be added**:
When creating a service of type `LoadBalancer` backed by an LB with a public IP a security group has to be created in order to expose it to the external. AFAIK today the responsibility of doing this is on the user, I propose to add an option to have the CCM taking care of this similarly to what [OpenStack CCM is doing](https://github.com/kubernetes/cloud-provider-openstack/blob/0dfdb1c5e22f59ee1f09198a0eb68f0716dd1ec5/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L1333).

**Why is this needed**:
To simplify and automate services exposal.

**Comment by RainbowMango** [comment]
That makes sense.  I need to investigate first.
