### ISSUE TITLE
Add doc to manage huawei cloud provier on Rancher

### ISSUE THREAD

**Issue by mikaelmorvan** [kubernetes-sigs/cloud-provider-huaweicloud#94]
Hi,
**What would you like to be added**:

I'm using RKE (from Rancher) to deploy a Kubernetes cluster on a Huwai cloud cluster (Flexible Engine, Orange Group).

I can deploy a new cluster using the OpenStack cloud provider built in RKE but some specific functionnalities are missing like loadbalancer settings.

The documentation isn't clear enough to explain how to deploy and use the Huawei Cloud Provider, could you please give a detail (step by step ?) way to deploy it ?

**Why is this needed**:

Can't use specific Huawei Cloud settings for Kubernetes Cluster.

Thanks,
  Mikaël Morvan

**Comment by RainbowMango** [comment]
The [quick-start-with-local-cluster](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/docs/quick-start-with-local-cluster.md) describes how to run Huawei Cloud Provider on local clusters.

> The documentation isn't clear enough to explain how to deploy and use the Huawei Cloud Provider, could you please give a detail (step by step ?) way to deploy it ?

Do you mean you need some description about run provider in cluster?

**Comment by DafuSHI** [comment]
Hello Hongcai,

Thank you for your reply. Actually we would like some description how huaweicloud provider works with Rancher.
As shown in the guide: https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/
It mentions how to use openstack provider with Rancher while unfortunatly it can't choose private or public ELB.
We would like to use huaweicloud provider to better create ELB resources.
Could you help？

**Comment by RainbowMango** [comment]
Hi @mikaelmorvan, @DafuSHI 

Just quickly went through the guide and RKE implementations, I found that RKE provides specific implementations for each provider.  You can get the whole support list from [here](https://github.com/rancher/rke/blob/f176422daa4ea6d9a006ad65d4001060c673e338/types/rke_types.go#L503-L516).

So, seems RKE still not support huaweicloud provider for now. 

```
type CloudProvider struct {
	// Name of the Cloud Provider
	Name string `yaml:"name" json:"name,omitempty"`
	// AWSCloudProvider
	AWSCloudProvider *AWSCloudProvider `yaml:"awsCloudProvider,omitempty" json:"awsCloudProvider,omitempty"`
	// AzureCloudProvider
	AzureCloudProvider *AzureCloudProvider `yaml:"azureCloudProvider,omitempty" json:"azureCloudProvider,omitempty"`
	// OpenstackCloudProvider
	OpenstackCloudProvider *OpenstackCloudProvider `yaml:"openstackCloudProvider,omitempty" json:"openstackCloudProvider,omitempty"`
	// VsphereCloudProvider
	VsphereCloudProvider *VsphereCloudProvider `yaml:"vsphereCloudProvider,omitempty" json:"vsphereCloudProvider,omitempty"`
	// CustomCloudProvider is a multiline string that represent a custom cloud config file
	CustomCloudProvider string `yaml:"customCloudProvider,omitempty" json:"customCloudProvider,omitempty"`
}
```

**Comment by Edge94** [comment]
Hi,

Yes the huaweicloud provider is not supported by RKE but RKE seems to support custom cloud providers.

They provide [this](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/custom/) example.

The question is : How can we build and install the huawei cloud provider to be used with RKE ?

For the configuration, I hope something like openstack cloud provider should work.

```
[Global]
auth-url = xxxx
username = xxxx
password = xxxx
tenant-id = xxxx
domain-name = xxxx
region = xxxx

[LoadBalancer]
subnet-id = xxxx
```

Thank you for your help.

**Comment by rcarre** [comment]
> Hi,
> 
> Yes the huaweicloud provider is not supported by RKE but RKE seems to support custom cloud providers.
> 
> They provide [this](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/custom/) example.
> 
> The question is : How can we build and install the huawei cloud provider to be used with RKE ?
> 
> For the configuration, I hope something like openstack cloud provider should work.
> 
> ```
> [Global]
> auth-url = xxxx
> username = xxxx
> password = xxxx
> tenant-id = xxxx
> domain-name = xxxx
> region = xxxx
> 
> [LoadBalancer]
> subnet-id = xxxx
> ```
> 
> Thank you for your help.

Hello @Edge94,
the above configuration looks like Rancher in-tree cloud provider, doesn't it ? What about the alternative to trigger [cloud-provider-huaweicloud](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud) as a Rancher specific external cloud provider instead of [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) which does not support **non-Octavia API compatible** Huawei Cloud Load Balancer. Here is an [example](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/examples/CloudControllerManagerConfigurationExample.json) of such setup.

By the way @RainbowMango, does cloud-provider-huaweicloud plan to support [Dedicated Load Balancers](https://support.huaweicloud.com/intl/en-us/api-elb/CreateLoadBalancer.html) ? Thanks for you support.

**Comment by RainbowMango** [comment]
> By the way @RainbowMango, does cloud-provider-huaweicloud plan to support [Dedicated Load Balancers](https://support.huaweicloud.com/intl/en-us/api-elb/CreateLoadBalancer.html) ? Thanks for you support.

I'm glad to support the `Dedicate Load Balancer`, but I'm busy with other stuff, so no plan for it yet.
