### ISSUE TITLE
GET AUTHORIZATION ERROR WHEN USING LATEST K8S AND PROVIDER

### ISSUE THREAD

**Issue by Mametee** [kubernetes-sigs/cloud-provider-huaweicloud#95]
**What happened**:
![image](https://user-images.githubusercontent.com/33069605/93729742-6436de00-fbf8-11ea-9733-a55dfb622605.png)

This is my configuration
```
{
    "LoadBalancer": {
        "apiserver": "172.17.0.1:8080",
        "secretName": "huawei-ccm-secret",
        "signerType": "ec2",
        "elbAlgorithm": "roundrobin",
        "tenantId": "{tenant id}",
        "region": "eu-de",
        "vpcId": "{vpc id}",
        "subnetId": "{subnet id}",
        "ecsEndpoint": "https://ecs.eu-de.otc.t-systems.com",
        "elbEndpoint": "https://elb.eu-de.otc.t-systems.com",
        "albEndpoint": "https://elb.eu-de.otc.t-systems.com",
        "vpcEndpoint": "https://vpc.eu-de.otc.t-systems.com",
        "natEndpoint": "https://nat.eu-de.otc.t-systems.com",
        "enterpriseEnable": "false"
    },
    "Auth": {
        "SecretName": "",
        "AccessKey" : "{AccessKey}",
        "SecretKey" : "{SecretKey}",
        "IAMEndpoint": "https://iam.eu-de.otc.t-systems.com",
        "ECSEndpoint": "https://ecs.eu-de.otc.t-systems.com",
        "DomainID": "a01aafcf63744d988ebef2b1e04c5c34",
        "ProjectID": "bf74229f30c0421fae270386a43315ee",
        "Region": "eu-de",
        "Cloud": "otc.t-systems.com"
    }
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.0-alpha.0.1400+bd39d3933be27d-dirty
- Cloud provider or hardware configuration: mentioned early
- OS (e.g: `cat /etc/os-release`):  CentOS Linux 7 
- Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by RainbowMango** [comment]
There is a similar error message from https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/issues/76#issuecomment-667866477, that because the API gateway version still using v3.

Please confirm which API gateway version you are using, only v4 is allowed. Thanks.

**Comment by Mametee** [comment]
Yeah, it is same problem with  https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/issues/76#issuecomment-667866477

**Comment by Mametee** [comment]
I have changed the http.go and rebuild the program by following https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/issues/76#issuecomment-667866477.  

I got  same result.
![image](https://user-images.githubusercontent.com/33069605/93855412-097daf00-fcea-11ea-96c4-44028a84a40b.png)

More support needed!!
